version: '3.8'

networks:
  erdemio-network:
    driver: bridge

services:
  backend:
    image: drogbach/ep-backend:latest
    build:
      context: ./ep-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ep_database
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=7hkyN11iMVJM0lZy0ZuE
    depends_on:
      - db
    networks:
      - erdemio-network

  frontend:
    image: drogbach/ep-frontend:latest
    build:
      context: ./ep-frontend
    ports:
      - "3000:3000"
    depends_on:
      - openapi-generator
    networks:
      - erdemio-network

  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./ep-frontend:/local
    command: >
      /bin/sh -c "wget -qO- http://backend:8080/erdem-project/v3/api-docs
      | java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate
      -i /dev/stdin
      -g typescript-fetch
      -o /local/src/api-client"

  db:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ep_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: 7hkyN11iMVJM0lZy0ZuE
      MYSQL_ROOT_PASSWORD: 7hkyN11iMVJM0lZy0ZuE
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - erdemio-network

volumes:
  db-data: