/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskEntity
 */
export interface TaskEntity {
    /**
     * 
     * @type {string}
     * @memberof TaskEntity
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof TaskEntity
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskEntity
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof TaskEntity
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskEntity
     */
    text?: string;
    /**
     * 
     * @type {Date}
     * @memberof TaskEntity
     */
    begin?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskEntity
     */
    end?: Date;
}

/**
 * Check if a given object implements the TaskEntity interface.
 */
export function instanceOfTaskEntity(value: object): boolean {
    return true;
}

export function TaskEntityFromJSON(json: any): TaskEntity {
    return TaskEntityFromJSONTyped(json, false);
}

export function TaskEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'title': json['title'] == null ? undefined : json['title'],
        'text': json['text'] == null ? undefined : json['text'],
        'begin': json['begin'] == null ? undefined : (new Date(json['begin'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
    };
}

export function TaskEntityToJSON(value?: TaskEntity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'title': value['title'],
        'text': value['text'],
        'begin': value['begin'] == null ? undefined : ((value['begin']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
    };
}

