/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WeatherDescriptionType } from './WeatherDescriptionType';
import {
    WeatherDescriptionTypeFromJSON,
    WeatherDescriptionTypeFromJSONTyped,
    WeatherDescriptionTypeToJSON,
} from './WeatherDescriptionType';

/**
 * 
 * @export
 * @interface WeatherDTO
 */
export interface WeatherDTO {
    /**
     * 
     * @type {number}
     * @memberof WeatherDTO
     */
    temperature: number;
    /**
     * 
     * @type {WeatherDescriptionType}
     * @memberof WeatherDTO
     */
    description: WeatherDescriptionType;
    /**
     * 
     * @type {string}
     * @memberof WeatherDTO
     */
    city: string;
}

/**
 * Check if a given object implements the WeatherDTO interface.
 */
export function instanceOfWeatherDTO(value: object): boolean {
    if (!('temperature' in value)) return false;
    if (!('description' in value)) return false;
    if (!('city' in value)) return false;
    return true;
}

export function WeatherDTOFromJSON(json: any): WeatherDTO {
    return WeatherDTOFromJSONTyped(json, false);
}

export function WeatherDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'temperature': json['temperature'],
        'description': WeatherDescriptionTypeFromJSON(json['description']),
        'city': json['city'],
    };
}

export function WeatherDTOToJSON(value?: WeatherDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'temperature': value['temperature'],
        'description': WeatherDescriptionTypeToJSON(value['description']),
        'city': value['city'],
    };
}

