/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WeatherDescriptionType = {
    Clear: 'CLEAR',
    Clouds: 'CLOUDS',
    Snow: 'SNOW',
    Rain: 'RAIN',
    Drizzle: 'DRIZZLE',
    Thunderstorm: 'THUNDERSTORM'
} as const;
export type WeatherDescriptionType = typeof WeatherDescriptionType[keyof typeof WeatherDescriptionType];


export function WeatherDescriptionTypeFromJSON(json: any): WeatherDescriptionType {
    return WeatherDescriptionTypeFromJSONTyped(json, false);
}

export function WeatherDescriptionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherDescriptionType {
    return json as WeatherDescriptionType;
}

export function WeatherDescriptionTypeToJSON(value?: WeatherDescriptionType | null): any {
    return value as any;
}

