/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MailDTO,
} from '../models/index';
import {
    MailDTOFromJSON,
    MailDTOToJSON,
} from '../models/index';

export interface SendMailRequest {
    mailDTO: MailDTO;
}

/**
 * 
 */
export class MailControllerApi extends runtime.BaseAPI {

    /**
     * Endpoint to send an email through a contact form.
     * Send Email via Contact Form
     */
    async sendMailRaw(requestParameters: SendMailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['mailDTO'] == null) {
            throw new runtime.RequiredError(
                'mailDTO',
                'Required parameter "mailDTO" was null or undefined when calling sendMail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/mail/send`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MailDTOToJSON(requestParameters['mailDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Endpoint to send an email through a contact form.
     * Send Email via Contact Form
     */
    async sendMail(requestParameters: SendMailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendMailRaw(requestParameters, initOverrides);
    }

}
